# hello_world.yml
---
- name: My first Ansible Hello World with variable input
  hosts: localhost
  vars:
    - name: "my_message"
 
  tasks:
    - name: Print the custom message
      debug:
        msg: "{{my_message}}"